package com.mycompany.pages;

// Import(s)
import com.mycompany.api.APIFactory;
import com.mycompany.api.Delete;
import com.mycompany.api.FactoryCreator;
import com.mycompany.api.Get;
import com.mycompany.entity.Booking;
import com.mycompany.entity.User;
import com.mycompany.covidsystem.ControlPanel;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * This class represents the modify booking page for admins
 */
public class AdminModifyBookingPage extends javax.swing.JPanel {
    
    // Manually included variable(s)
    private static final ControlPanel controlPanel = ControlPanel.getControlPanel();
    private static User currentUser;
    private List<Booking> bookings = new ArrayList<>();
    private List<Booking> testingSiteBookings;
    private static final APIFactory<Booking> bookingFactory = FactoryCreator.getBookingFactory();
    private String selectedBookingId;
    private Get<Booking> bookingGet = bookingFactory.createGet();
    private Delete bookingDelete = bookingFactory.createDelete();
    private Booking currentBooking;
    private String testingSiteId;
    public static final int SINGLE_CLICK = 1;
    
    /**
     * Creates new form AdminModifyBookingPage
     */
    public AdminModifyBookingPage() {
        initComponents();
    }
    
    //Get all bookings from the testing site that the admin is working at
    public void getTestingSiteBookings(){
        testingSiteBookings = new ArrayList<>();
        testingSiteId = currentUser.getAdditionalInfo().getTesingSiteId();
        try{
            bookings = bookingGet.createGetRequest();
        }catch (Exception e)
        {
            e.printStackTrace();
        }
        
        for (Booking booking: bookings){
            if (booking.getTestingSite().getId().equals(testingSiteId)){
                testingSiteBookings.add(booking);
            }
        }
    }
    
    //show all bookings from the testing site that the admin is working at
    public void showTestingSiteBookings(){
        String bookingId;
        String customerId;
        String startTime;
        String status;
        
        DefaultTableModel tblModel = (DefaultTableModel)bookingsTable.getModel();
        tblModel.setRowCount(0);//reset table before repopulating with new data 
        
        //get specific infos from each booking and store in a list
        for (Booking booking: testingSiteBookings){
            bookingId = booking.getId();
            customerId = booking.getCustomer().getId();
            startTime = booking.getStartTime();
            status = booking.getStatus();
            
            Object data[] = {bookingId, customerId, startTime, status};
            
            tblModel.addRow(data);
        }
        
    }
    
    //Set the current user that is logged in 
    public void setAdminUser(User user){
        currentUser = user;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingsTable = new javax.swing.JTable();
        logOutBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        bookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Start Time", "Status"
            }
        ));
        bookingsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        bookingsTable.setDefaultEditor(Object.class, null);
        bookingsTable.setShowHorizontalLines(true);
        bookingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingsTable);

        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        modifyBtn.setText("Modify");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logOutBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyBtn)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutBtn)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(modifyBtn))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Redirects user to choose a page 
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        controlPanel.showReceptionistPage();
    }//GEN-LAST:event_backBtnActionPerformed

    //Logs the user out of the system
    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        controlPanel.logOut();
    }//GEN-LAST:event_logOutBtnActionPerformed
    
    //Directs admin users to the ModifyBookingPage
    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        for (Booking booking: bookings){
            if(booking.getId().equals(selectedBookingId)){
                currentBooking = booking;
            }
        }
        controlPanel.showModifyBookingPage(currentBooking);
    }//GEN-LAST:event_modifyBtnActionPerformed

    //Allows admin to delete a booking
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try{
            bookingDelete.createDeleteRequest(selectedBookingId);
            JOptionPane.showMessageDialog(null, "Bookind id " + selectedBookingId + " is deleted" , "Delete Booking", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e ){
            JOptionPane.showMessageDialog(null, "A booking cannot be deleted if it has an associated covid test" , "Delete Booking", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
    
    //Method for when a row of booking is clicked
    private void bookingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsTableMouseClicked
        if (evt.getClickCount() == SINGLE_CLICK && evt.getButton() == MouseEvent.BUTTON1)
        {
            int selectedBookingIndex = bookingsTable.getSelectedRow();
            Object bookingIdCell = bookingsTable.getValueAt(selectedBookingIndex, 0);
            selectedBookingId = bookingIdCell.toString();
        }
    }//GEN-LAST:event_bookingsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookingsTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton modifyBtn;
    // End of variables declaration//GEN-END:variables
}
