package com.mycompany.pages;

// Import(s)
import com.mycompany.entity.Booking;
import com.mycompany.api.*;
import com.mycompany.covidsystem.ControlPanel;
import com.mycompany.entity.Customer;
import com.mycompany.entity.User;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * This class represents the check user status page
 */
public class CheckUserStatusPage extends javax.swing.JPanel {

    // Manually included variable(s)
    private static final ControlPanel controlPanel = ControlPanel.getControlPanel();
    private static final APIFactory<Booking> bookingFactory = FactoryCreator.getBookingFactory();
    
    /**
     * Creates new form CheckUserStatusPage
     */
    public CheckUserStatusPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smsPinPanel = new javax.swing.JPanel();
        smsPinLabel = new javax.swing.JLabel();
        smsPinTextField = new javax.swing.JTextField();
        checkStatusButton = new javax.swing.JButton();
        bookingIdTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        bookingIdLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        startTimeTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        smsPinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smsPinLabel.setText("SMS PIN:");

        checkStatusButton.setText("Check Status");
        checkStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStatusButtonActionPerformed(evt);
            }
        });

        bookingIdTextField.setEditable(false);

        customerNameTextField.setEditable(false);

        statusLabel.setText("Status:");

        startTimeLabel.setText("Start Time:");

        bookingIdLabel.setText("Booking ID:");

        customerNameLabel.setText("Customer Name:");

        statusTextField.setEditable(false);

        startTimeTextField.setEditable(false);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smsPinPanelLayout = new javax.swing.GroupLayout(smsPinPanel);
        smsPinPanel.setLayout(smsPinPanelLayout);
        smsPinPanelLayout.setHorizontalGroup(
            smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smsPinPanelLayout.createSequentialGroup()
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smsPinPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookingIdLabel)
                            .addComponent(customerNameLabel)
                            .addComponent(statusLabel)
                            .addComponent(startTimeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameTextField)
                            .addComponent(bookingIdTextField)
                            .addComponent(startTimeTextField)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(smsPinPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(smsPinLabel)
                        .addGap(18, 18, 18)
                        .addComponent(smsPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(smsPinPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        smsPinPanelLayout.setVerticalGroup(
            smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smsPinPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkStatusButton)
                    .addComponent(smsPinLabel)
                    .addComponent(smsPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIdLabel)
                    .addComponent(bookingIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(startTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(smsPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(logoutButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(smsPinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(smsPinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    // This method checks the booking status of a user using SMS PIN
    // Displays the status along with other details
    private void checkStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusButtonActionPerformed
        try
        {
            Get<Booking> bookingGet = bookingFactory.createGet();
            List<Booking>bookings = bookingGet.createGetRequest();
            Booking booking = null;
            for (Booking b: bookings)
            {
                if (b.getSmsPin().equals(smsPinTextField.getText()))
                {
                    booking = b;
                }
            }

            Customer customer = booking.getCustomer();
            String customerName = customer.getFamilyName() + " " + customer.getGivenName();
            customerNameTextField.setText(customerName);
            bookingIdTextField.setText(booking.getId());
            startTimeTextField.setText(booking.getStartTime());
            statusTextField.setText(booking.getStatus()); 
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }    
    }//GEN-LAST:event_checkStatusButtonActionPerformed

    // This method is used to bring a user back to the login page
    // It is called when a button is clicked
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        controlPanel.logOut();
    }//GEN-LAST:event_logoutButtonActionPerformed

    // This method is used to bring a user back to the dialog
    // The dialog allows navigation to other pages
    // It is called when a button is clicked
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        User user = controlPanel.getCurrentUser();
        
        // This page is designated for a customer and receptionist
        // So a role checking condition is needed
        // To bring them back to their designated pages
        if (user.isCustomer().booleanValue() == true)
        {
            controlPanel.showCustomerPage();
        }
        else if (user.isReceptionist().booleanValue() == true)
        {
            controlPanel.showReceptionistPage();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookingIdLabel;
    private javax.swing.JTextField bookingIdTextField;
    private javax.swing.JButton checkStatusButton;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel smsPinLabel;
    private javax.swing.JPanel smsPinPanel;
    private javax.swing.JTextField smsPinTextField;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JTextField startTimeTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}