package com.mycompany.pages;

// Import(s)
import com.mycompany.api.*;
import com.mycompany.covidsystem.ControlPanel;
import com.mycompany.entity.Booking;
import java.sql.Timestamp;
import java.time.Instant;
import javax.swing.JOptionPane;

/**
 * This class represents the onsite booking page
 */
public class OnsiteBookingPage extends javax.swing.JPanel {

    private static final ControlPanel controlPanel = ControlPanel.getControlPanel();
    private static final APIFactory<Booking> bookingFactory = FactoryCreator.getBookingFactory();

    /**
     * Creates new form OnsiteBookingPage
     */
    public OnsiteBookingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        onsiteBookingConfirmPanel = new javax.swing.JPanel();
        customerIdTextField = new javax.swing.JTextField();
        customerIdLabel = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        patientIdLabel = new javax.swing.JLabel();
        testingSiteIdTextField = new javax.swing.JTextField();
        testingSiteId = new javax.swing.JLabel();
        confirmBookingButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        onsiteBookingConfirmPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        onsiteBookingConfirmPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        customerIdLabel.setText("Customer ID:");

        patientIdLabel.setText("Patient ID:");

        testingSiteId.setText("Testing Site ID:");

        confirmBookingButton.setText("Confirm Booking");
        confirmBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout onsiteBookingConfirmPanelLayout = new javax.swing.GroupLayout(onsiteBookingConfirmPanel);
        onsiteBookingConfirmPanel.setLayout(onsiteBookingConfirmPanelLayout);
        onsiteBookingConfirmPanelLayout.setHorizontalGroup(
            onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onsiteBookingConfirmPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(onsiteBookingConfirmPanelLayout.createSequentialGroup()
                .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(onsiteBookingConfirmPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerIdLabel)
                            .addComponent(patientIdLabel)
                            .addComponent(testingSiteId))
                        .addGap(18, 18, 18)
                        .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patientIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testingSiteIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(onsiteBookingConfirmPanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(confirmBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        onsiteBookingConfirmPanelLayout.setVerticalGroup(
            onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onsiteBookingConfirmPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdLabel)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLabel)
                    .addComponent(patientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testingSiteId)
                    .addComponent(testingSiteIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(confirmBookingButton)
                .addGap(66, 66, 66)
                .addGroup(onsiteBookingConfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(backButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(onsiteBookingConfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(onsiteBookingConfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    // This method creates a Booking object and stores data
    private void confirmBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        
        // Get current time when onsite booking is made as start time
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        Instant instant = timestamp.toInstant();
        String startTime = instant.toString();
        
        try 
        {
            Post bookingPost = bookingFactory.createPost();
            bookingPost.createPostRequest(customerIdTextField.getText(), testingSiteIdTextField.getText(), startTime);
            JOptionPane.showMessageDialog(null, "Booking has been confirmed.", "Booking Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }                                                    

    // This method is used to bring a user back to the login page
    // It is called when a button is clicked
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        controlPanel.logOut();
    }                                            

    // This method is used to bring a user back to the dialog
    // The dialog allows navigation to other pages
    // It is called when a button is clicked
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        controlPanel.showReceptionistPage();
    }                                          

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmBookingButton;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel onsiteBookingConfirmPanel;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JLabel testingSiteId;
    private javax.swing.JTextField testingSiteIdTextField;
    // End of variables declaration                   
}